name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3

      - name: Use NPM install
        uses: bahmutov/npm-install@v1
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ job.status == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3

      - name: Use NPM install
        uses: bahmutov/npm-install@v1
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Test
        run: yarn vitest
  build:
    runs-on: ubuntu-latest
    needs: [test]
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3

      - name: Use NPM install
        uses: bahmutov/npm-install@v1
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
